version: 2
jobs:
  ci-client:
    working_directory: ~/highscore
    docker:
      - image: circleci/node:12.12.0-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Lint Project
          command: npm run ng:lint
      - run:
          name: Testing
          command: npm test
      # - run:
      #     name: End to End Test
      #     command: npm run e2e -- --protractor-config=e2e/protractor.conf.js
      - run:
          name: Production Build
          command: npm ng:build --prod --aot
